// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: config/conf_server.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mac struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *Mac) Reset() {
	*x = Mac{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_conf_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mac) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mac) ProtoMessage() {}

func (x *Mac) ProtoReflect() protoreflect.Message {
	mi := &file_config_conf_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mac.ProtoReflect.Descriptor instead.
func (*Mac) Descriptor() ([]byte, []int) {
	return file_config_conf_server_proto_rawDescGZIP(), []int{0}
}

func (x *Mac) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Vendor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Vendor string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Octets string `protobuf:"bytes,3,opt,name=octets,proto3" json:"octets,omitempty"`
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_conf_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_config_conf_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_config_conf_server_proto_rawDescGZIP(), []int{1}
}

func (x *Vendor) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Vendor) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Vendor) GetOctets() string {
	if x != nil {
		return x.Octets
	}
	return ""
}

var File_config_conf_server_proto protoreflect.FileDescriptor

var file_config_conf_server_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6f, 0x6e, 0x66,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1b, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x4e, 0x0a, 0x06, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x63, 0x74, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x63,
	0x74, 0x65, 0x74, 0x73, 0x32, 0x4a, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x56, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x12, 0x3a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x63, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0x00,
	0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x2f, 0x67, 0x65, 0x6e, 0x3b,
	0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_conf_server_proto_rawDescOnce sync.Once
	file_config_conf_server_proto_rawDescData = file_config_conf_server_proto_rawDesc
)

func file_config_conf_server_proto_rawDescGZIP() []byte {
	file_config_conf_server_proto_rawDescOnce.Do(func() {
		file_config_conf_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_conf_server_proto_rawDescData)
	})
	return file_config_conf_server_proto_rawDescData
}

var file_config_conf_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_conf_server_proto_goTypes = []interface{}{
	(*Mac)(nil),    // 0: conf_server.Mac
	(*Vendor)(nil), // 1: conf_server.Vendor
}
var file_config_conf_server_proto_depIdxs = []int32{
	0, // 0: conf_server.SearchVendor.GetSearchVendor:input_type -> conf_server.Mac
	1, // 1: conf_server.SearchVendor.GetSearchVendor:output_type -> conf_server.Vendor
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_conf_server_proto_init() }
func file_config_conf_server_proto_init() {
	if File_config_conf_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_conf_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mac); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_conf_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vendor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_conf_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_conf_server_proto_goTypes,
		DependencyIndexes: file_config_conf_server_proto_depIdxs,
		MessageInfos:      file_config_conf_server_proto_msgTypes,
	}.Build()
	File_config_conf_server_proto = out.File
	file_config_conf_server_proto_rawDesc = nil
	file_config_conf_server_proto_goTypes = nil
	file_config_conf_server_proto_depIdxs = nil
}
